python ddw.py \
    --plugin /Library/Audio/Plug-Ins/VST/Serum.vst \
    --preset-dir ../fxp_preset/lead \
    --sample-rate 44100 \
    --bpm 120 \
    --note-duration 2 \
    --pitch-low 60 \
    --pitch-high 60 \
    --render-duration 4 \
    --num-workers 1 \
    --output-dir ../rendered_audio/lead \
    --log-level INFO